### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [rndeshpande/NYTArticleSearch#1]
:+1: Great work! A few notes after checking out the code:

* Try externalizing few methods (like `isNetworkAvailable`) to util class for re-usability
* Properly reused the single base method in search activity to fetch results for both initial load and the pagination
* Properly used spinners/checkboxes (with populated values) to allow users to select filters
* Good to see you used model objects to represent the filters to apply to the query
* Great job implementing `DialogFragment` for filters.
* Nice to see you added the search box to the `Toolbar`!
* Nice job adding the share intent to the article detail view!
* Make sure to try the new [date picker](http://guides.codepath.com/android/Using-DialogFragment#displaying-date-or-time-picker-dialogs) dialog. 

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.

**Comment by rndeshpande** [comment]
Thanks and really appreciate the feedback. Based on the UI and Code score for the last two assignments, I was wondering if I could get a little more detailed feedback on my work so I can uncover and fix some common issues. Please let me know if someone would be able to spend some time with me on this.

**Comment by codepathreview** [comment]
Overall, code & UI looks good. If you want to challenge yourself further, try out using [Modern Android Architecture](https://guides.codepath.com/android/Architecture-of-Android-Apps) for your next assignment,
